Repository backdorJ/Russian-Spotify, pull requests merged in 2024-05, with the labels that each got.

#61 Feature/create about page
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Account/PatchUpdateUserInfo/PatchUpdateUserInfoCommandHandler.cs
  spotify-react-app/package-lock.json
  spotify-react-app/package.json
  spotify-react-app/src/assets/cSharp.png
  spotify-react-app/src/assets/damir_team.jpg
  spotify-react-app/src/assets/irek_team.jpg
  spotify-react-app/src/assets/marat_team.jpg
  spotify-react-app/src/assets/mediatR.png
  spotify-react-app/src/assets/postgres.png
  spotify-react-app/src/assets/react-logo.png
  spotify-react-app/src/assets/sidebar/about.png
  spotify-react-app/src/assets/team_vanya.jpg
  spotify-react-app/src/pages/AboutPage/AboutPage.tsx
  spotify-react-app/src/pages/AboutPage/components/AboutCard.tsx
  spotify-react-app/src/pages/AboutPage/styles/AboutPage.css
  spotify-react-app/src/utils/about/aboutPlacemarksOptions.ts
  spotify-react-app/src/utils/about/aboutTeamImages.ts
  spotify-react-app/src/utils/about/aboutTechnologies.ts
  spotify-react-app/src/utils/routeNames.ts
  spotify-react-app/src/utils/routes.ts
  spotify-react-app/src/utils/sidebar/navigationElementsProps.ts
Labels: enhancement

#60 bugfix/player-and-songs-functions
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Services/Filters/PlaylistFilter/AuthorPlaylistsFilter.cs
  spotify-react-app/package-lock.json
  spotify-react-app/src/assets/mock/common/PlayIcon.tsx
  spotify-react-app/src/assets/mock/playlistpage/songs/liked.png
  spotify-react-app/src/commonComponents/FavouriteMusic/FavouriteMusic.tsx
  spotify-react-app/src/commonComponents/FavouriteMusic/Interfaces/IFavouriteMusic.ts
  spotify-react-app/src/commonComponents/FavouriteMusic/styles/FavouriteMusic.css
  spotify-react-app/src/commonComponents/FavouritePlaylist/FavouritePlaylist.tsx
  spotify-react-app/src/commonComponents/FavouritePlaylist/interfaces/IFavouritePlaylist.ts
  spotify-react-app/src/commonComponents/Player/Player.tsx
  spotify-react-app/src/commonComponents/Player/components/CurrentPlaylistIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/LikeIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/NextIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/PrevIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/StartIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/StartStopIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/StopIcon.tsx
  spotify-react-app/src/commonComponents/Player/styles/Player.css
  spotify-react-app/src/commonComponents/SideBar/components/CreateOrEditPlaylistModal/CreateOrEditPlaylistModal.tsx
  spotify-react-app/src/commonComponents/SideBar/components/CreateOrEditSongModal/CreateOrEditSongModal.tsx
  spotify-react-app/src/commonComponents/Song/Song.tsx
  spotify-react-app/src/commonComponents/Song/styles/Song.css
  spotify-react-app/src/commonComponents/SongCard/SongCard.tsx
  spotify-react-app/src/commonComponents/SongCard/interfaces/IEditSongAuthors.ts
  spotify-react-app/src/commonComponents/SongCard/interfaces/ISongCard.ts
  spotify-react-app/src/commonComponents/SongCard/styles/SongCard.css
  spotify-react-app/src/http/playlistApi.ts
  spotify-react-app/src/http/songApi.ts
  spotify-react-app/src/models/Player.ts
  spotify-react-app/src/models/Playlist.ts
  spotify-react-app/src/pages/AccountPage/AccountPage.tsx
  spotify-react-app/src/pages/AccountPage/components/FavoriteMusic.tsx
  spotify-react-app/src/pages/AccountPage/components/interfaces/IFavoriteMusic.ts
  spotify-react-app/src/pages/AccountPage/styles/AccountPage.css
  spotify-react-app/src/pages/AuthorPage/AuthorPage.tsx
  spotify-react-app/src/pages/HomePage/styles/HomePage.css
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/PlaylistPage/components/SongCard.tsx
  spotify-react-app/src/pages/PlaylistPage/components/modals/EditSongAuthorModal/EditSongAuthorModal.tsx
  spotify-react-app/src/pages/PlaylistPage/styles/PlaylistPage.css
  spotify-react-app/src/pages/SearchPage/SearchPage.tsx
  spotify-react-app/src/pages/SearchPage/components/SearchAuthorCard.tsx
  spotify-react-app/src/pages/SearchPage/styles/SearchPage.css
  spotify-react-app/src/stores/playerStore.ts
Labels: enhancement, bugfix

#63 Feature/create seeder categories
  RussianSpotify.API/RussianSpotify.API.Contracts/Enums/CategoryTypes.cs
  RussianSpotify.API/RussianSpotify.API.Core/Entities/Category.cs
  RussianSpotify.API/RussianSpotify.API.Data.PostgreSQL/Seeder/DbSeeder.cs
Labels: enhancement

#64 About page get playlists короче лень писать сами посмотрите
  RussianSpotify.API/RussianSpotify.API.Core/Abstractions/IDbContext.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/GetPlaylistsByFilter/GetPlaylistsByFilterQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Services/Filters/PlaylistFilter/UserPlaylistsFilter.cs
  spotify-react-app/src/assets/vanya_photo.jpg
  spotify-react-app/src/commonComponents/SongCard/SongCard.tsx
  spotify-react-app/src/http/filters/playlistFilters.ts
  spotify-react-app/src/http/playlistApi.ts
  spotify-react-app/src/pages/AboutPage/components/AboutCard.tsx
  spotify-react-app/src/pages/AboutPage/styles/AboutPage.css
  spotify-react-app/src/utils/about/aboutTeamImages.ts
Labels: bugfix

#65 Frontend: Search Page pagination
  spotify-react-app/package-lock.json
  spotify-react-app/src/commonComponents/Player/Player.tsx
  spotify-react-app/src/commonComponents/SideBar/components/CreateOrEditSongModal/CreateOrEditSongModal.tsx
  spotify-react-app/src/commonComponents/SongCard/SongCard.tsx
  spotify-react-app/src/commonComponents/SongCard/styles/SongCard.css
  spotify-react-app/src/functions/loadDynamicSongs.ts
  spotify-react-app/src/http/authorApi.ts
  spotify-react-app/src/http/playlistApi.ts
  spotify-react-app/src/http/songApi.ts
  spotify-react-app/src/models/Song.ts
  spotify-react-app/src/pages/AccountPage/AccountPage.tsx
  spotify-react-app/src/pages/HomePage/HomePage.tsx
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/PlaylistPage/styles/PlaylistPage.css
  spotify-react-app/src/pages/SearchPage/SearchPage.tsx
  spotify-react-app/src/utils/dto/playlist/getPlaylists.ts
  spotify-react-app/src/utils/dto/song/getSongs.ts
  spotify-react-app/src/utils/song/songSources.ts
Labels: enhancement

#67 Bugfix/current playlist
  spotify-react-app/src/assets/sidebar/like.png
  spotify-react-app/src/commonComponents/Player/Player.tsx
  spotify-react-app/src/commonComponents/Player/components/CloseExpandedPlayer.tsx
  spotify-react-app/src/commonComponents/Player/components/NextIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/PrevIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/StartIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/StopIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/VolumeIcon.tsx
  spotify-react-app/src/commonComponents/Player/styles/Player.css
  spotify-react-app/src/commonComponents/SideBar/SideBar.tsx
  spotify-react-app/src/commonComponents/SongCard/SongCard.tsx
  spotify-react-app/src/commonComponents/SongCard/styles/SongCard.css
  spotify-react-app/src/http/authorApi.ts
  spotify-react-app/src/models/AuthorPage.ts
  spotify-react-app/src/models/Playlist.ts
  spotify-react-app/src/pages/AboutPage/styles/AboutPage.css
  spotify-react-app/src/pages/AccountPage/styles/AccountPage.css
  spotify-react-app/src/pages/AuthorPage/AuthorPage.tsx
  spotify-react-app/src/pages/LoginPage/components/AuthForm/styles/AuthForm.css
  spotify-react-app/src/pages/LoginPage/styles/LoginPage.css
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/PlaylistPage/styles/PlaylistPage.css
  spotify-react-app/src/pages/RegisterPage/components/InputRegisterWidget/styles/InputRegisterWidget.css
  spotify-react-app/src/pages/RegisterPage/components/RegForm/styles/RegForm.css
  spotify-react-app/src/pages/RegisterPage/styles/RegisterPage.css
  spotify-react-app/src/pages/ResetPasswordPage/styles/ResetPasswordPage.css
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.css
Labels: bugfix

#72 Bugfix/cosmetics
  spotify-react-app/src/commonComponents/SongCard/styles/SongCard.css
  spotify-react-app/src/pages/AboutPage/styles/AboutPage.css
  spotify-react-app/src/pages/AccountPage/styles/AccountPage.css
  spotify-react-app/src/pages/LoginPage/components/AuthForm/styles/AuthForm.css
  spotify-react-app/src/pages/PlaylistPage/styles/PlaylistPage.css
  spotify-react-app/src/pages/RegisterPage/components/InputRegisterWidget/styles/InputRegisterWidget.css
  spotify-react-app/src/pages/RegisterPage/components/RegForm/styles/RegForm.css
  spotify-react-app/src/pages/RegisterPage/styles/RegisterPage.css
  spotify-react-app/src/pages/ResetPasswordPage/styles/ResetPasswordPage.css
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.css
Labels: bugfix

#73 Frontend: Подправил страницу песен автора и карточку песни.
  spotify-react-app/src/commonComponents/FavouriteMusic/FavouriteMusic.tsx
  spotify-react-app/src/commonComponents/SongCard/SongCard.tsx
  spotify-react-app/src/utils/routeNames.ts
  spotify-react-app/src/utils/routes.ts
  spotify-react-app/src/utils/settings/settingsPages.tsx
Labels: enhancement, bugfix

#74 починил админку front, рефактор бэка
  RussianSpotify.Admin.API/russian-spotify-admin-api/package-lock.json
  RussianSpotify.Admin.API/russian-spotify-admin-api/package.json
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/app.module.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/config/allowedOrigins.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/config/corsOptions.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/main.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/DTOs/authorStatistic/GetAuthorStatisticRequestDto.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/DTOs/authorStatistic/GetAuthorStatisticResponseDto.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/DTOs/common/BaseGetStatisticRequestDto.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/DTOs/common/BaseGetStatisticResponseDto.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/DTOs/subscriptionStatistic/GetSubscriptionsStatisticResponseDto.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/DTOs/userStatistic/GetUsersStatisticResponseDto.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/controllers/authorStatistic.controller.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/controllers/subscriptionsStatistic.controller.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/controllers/usersStatistic.controller.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/modules/statistic/statistic.module.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/services/databaseInteraction/usersService.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/services/statistic/authorsStatisticService.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/services/statistic/subscriptionsStatisticService.ts
  RussianSpotify.Admin.API/russian-spotify-admin-api/src/services/statistic/usersStatisticService.ts
  RussianSpotify.Admin.UI/package-lock.json
Labels: bugfix, refactor
