Repository backdorJ/Russian-Spotify, pull requests merged in 2024-04, with the labels that each got.

#22 [bugfix/update-user-info]
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Account/PatchUpdateUserInfo/PatchUpdateUserInfoCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/OAuth/GetExternalLoginCallback/GetExternalLoginCallbackCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Middlewares/ExceptionMiddleware.cs
Labels: bugfix

#21 Frontend: user info update
  spotify-react-app/src/App.tsx
  spotify-react-app/src/functions/loadUser.ts
  spotify-react-app/src/http/authApi.ts
  spotify-react-app/src/pages/LoginPage/components/AuthForm/AuthForm.tsx
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.css
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.tsx
  spotify-react-app/src/pages/SettingsPage/components/settingsPersonal.tsx
  spotify-react-app/src/pages/SettingsPage/styles/SettingsPage.css
  spotify-react-app/src/utils/dto/user/userEditDto.ts
Labels: enhancement

#25 Frontend: Playlist Page (without api)
  spotify-react-app/src/App.css
  spotify-react-app/src/App.tsx
  spotify-react-app/src/assets/mock/playlistpage/like.png
  spotify-react-app/src/assets/mock/playlistpage/options_icon.png
  spotify-react-app/src/assets/mock/playlistpage/player_triangle.png
  spotify-react-app/src/assets/mock/playlistpage/playlist_page_placeholder.png
  spotify-react-app/src/assets/mock/playlistpage/songs/liked.png
  spotify-react-app/src/assets/mock/playlistpage/songs/liked_icon_svg.svg
  spotify-react-app/src/assets/mock/playlistpage/songs/slow_grenade_img.png
  spotify-react-app/src/commonComponents/NavBar/NavBar.css
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/PlaylistPage/components/SongCard.tsx
  spotify-react-app/src/pages/PlaylistPage/styles/PlaylistPage.css
  spotify-react-app/src/utils/routeNames.ts
  spotify-react-app/src/utils/routes.ts
Labels: enhancement

#27 Fullstack: Subscription bugfix
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Subscription/GetSubscription/GetSubscriptionResponse.cs
  RussianSpotify.API/RussianSpotify.API.Core/Services/SubscriptionHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/SubscriptionController.cs
Labels: bugfix

#28 Feature/play music
  RussianSpotify.API/RussianSpotify.API.Core/Exceptions/SubscriptionExceptions/UserSubscriptionHasExpiredException.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostLogin/PostLoginCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Music/GetSongContentById/GetSongContentByIdQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Configurations/ConfigureAuthenticationExtension.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/AuthController.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/FileController.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/SongController.cs
  spotify-react-app/.env
  spotify-react-app/package-lock.json
  spotify-react-app/package.json
  spotify-react-app/src/App.tsx
  spotify-react-app/src/assets/mock/common/PlayIcon.tsx
  spotify-react-app/src/commonComponents/AppRouter/AppRouter.tsx
  spotify-react-app/src/commonComponents/NavBar/NavBar.tsx
  spotify-react-app/src/commonComponents/NavBar/components/makeSubscriptionModal/makeSubscriptionModal.tsx
  spotify-react-app/src/commonComponents/Player/Player.tsx
  spotify-react-app/src/commonComponents/Player/components/NextIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/PrevIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/StartStopIcon.tsx
  spotify-react-app/src/commonComponents/Player/components/VolumeIcon.tsx
  spotify-react-app/src/commonComponents/Player/styles/Player.css
  spotify-react-app/src/commonComponents/Song/Song.tsx
  spotify-react-app/src/commonComponents/Song/interfaces/ISong.ts
  spotify-react-app/src/commonComponents/Song/styles/Song.css
  spotify-react-app/src/functions/isJwtDied.ts
  spotify-react-app/src/http/authApi.ts
  spotify-react-app/src/http/fileApi.ts
  spotify-react-app/src/http/index.ts
  spotify-react-app/src/http/songApi.ts
  spotify-react-app/src/index.tsx
  spotify-react-app/src/models/Player.ts
  spotify-react-app/src/models/Song.ts
  spotify-react-app/src/pages/AccountPage/AccountPage.tsx
  spotify-react-app/src/pages/AccountPage/components/FavoriteMusic.tsx
  spotify-react-app/src/pages/AccountPage/components/interfaces/IFavoriteMusic.ts
  spotify-react-app/src/pages/AccountPage/components/styles/FavoriteMusic.css
  spotify-react-app/src/pages/AccountPage/styles/AccountPage.css
  spotify-react-app/src/pages/HomePage/HomePage.tsx
  spotify-react-app/src/pages/LoginPage/LoginPage.tsx
  spotify-react-app/src/pages/LoginPage/components/AuthForm/AuthForm.tsx
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/RegisterPage/components/RegForm/RegForm.tsx
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.tsx
  spotify-react-app/src/pages/SettingsPage/components/settingsPersonal.tsx
  spotify-react-app/src/stores/playerStore.ts
  spotify-react-app/src/utils/dto/user/userLoginDto.ts
  spotify-react-app/tsconfig.json
Labels: enhancement

#31 [bug-fix/fix-context-name] fix
  spotify-react-app/src/commonComponents/NavBar/NavBar.tsx
  spotify-react-app/src/commonComponents/NavBar/components/makeSubscriptionModal/makeSubscriptionModal.tsx
Labels: bugfix

#34 Frontend: Made Sidebar
  spotify-react-app/.env
  spotify-react-app/.gitignore
  spotify-react-app/src/App.css
  spotify-react-app/src/App.tsx
  spotify-react-app/src/assets/sidebar/create_playlist.png
  spotify-react-app/src/assets/sidebar/home_icon.png
  spotify-react-app/src/assets/sidebar/library_icon.png
  spotify-react-app/src/assets/sidebar/liked_songs.png
  spotify-react-app/src/assets/sidebar/search_icon.png
  spotify-react-app/src/commonComponents/NavBar/NavBar.css
  spotify-react-app/src/commonComponents/NavBar/NavBar.tsx
  spotify-react-app/src/commonComponents/SideBar/SideBar.css
  spotify-react-app/src/commonComponents/SideBar/SideBar.tsx
  spotify-react-app/src/commonComponents/SideBar/components/CreatePlaylistModal/CreatePlaylistModal.css
  spotify-react-app/src/commonComponents/SideBar/components/CreatePlaylistModal/CreatePlaylistModal.tsx
  spotify-react-app/src/functions/createPlaylistWithFile.ts
  spotify-react-app/src/http/fileApi.ts
  spotify-react-app/src/http/playlistApi.ts
  spotify-react-app/src/utils/dto/playlist/createPlaylistDto.ts
  spotify-react-app/src/utils/sidebar/navigationElementsProps.ts
  spotify-react-app/src/utils/sidebar/playlistElementsProps.ts
Labels: enhancement

#37 Backend: Playlist Controller
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/PlaylistController.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/SongController.cs
  spotify-react-app/src/http/playlistApi.ts
Labels: enhancement, refactor

#36 Frontend: Search Page
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostRegister/PostRegisterCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Author/GetAuthor/GetAuthorQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Music/GetPlaylistsByFilter/GetPlaylistsByFilterQuery.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Music/GetPlaylistsByFilter/GetPlaylistsByFilterQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/AuthorController.cs
  spotify-react-app/src/assets/searchPage/search_icon_121212.png
  spotify-react-app/src/http/playlistApi.ts
  spotify-react-app/src/pages/SearchPage/SearchPage.tsx
  spotify-react-app/src/pages/SearchPage/components/SearchAuthorCard.tsx
  spotify-react-app/src/pages/SearchPage/components/SearchPlaylistCard.tsx
  spotify-react-app/src/pages/SearchPage/styles/SearchPage.css
  spotify-react-app/src/utils/mocks/homepage/discoveryCards.ts
  spotify-react-app/src/utils/mocks/homepage/playlistsNormal.ts
  spotify-react-app/src/utils/routeNames.ts
  spotify-react-app/src/utils/routes.ts
  spotify-react-app/src/utils/search/searchTypesProps.ts
  spotify-react-app/src/utils/sidebar/navigationElementsProps.ts
Labels: enhancement

#47 Удаление любимого плейлиста (Backend)
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/RemovePlaylistFromFavorite/RemovePlaylistFromFavoriteCommand.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/RemovePlaylistFromFavorite/RemovePlaylistFromFavoriteCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/PlaylistController.cs
Labels: enhancement

#49 Bugfix/auth back
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Auth/PostConfirmPasswordReset/PostConfirmPasswordResetRequest.cs
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Auth/PostResetPassword/PostResetPasswordRequest.cs
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Auth/PostResetPassword/PostResetPasswordResponse.cs
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Auth/PostValidatePasswordResetConfirmationToken/PostValidatePasswordResetConfirmationTokenRequest.cs
  RussianSpotify.API/RussianSpotify.API.Core/Enums/BaseCookieOptions.cs
  RussianSpotify.API/RussianSpotify.API.Core/Exceptions/AuthExceptions/InvalidTokenException.cs
  RussianSpotify.API/RussianSpotify.API.Core/Exceptions/AuthExceptions/WrongConfirmationTokenException.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Account/PatchUpdateUserInfo/PatchUpdateUserInfoCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostConfirmEmail/PostConfirmEmailCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostConfirmPasswordReset/PostConfirmPasswordResetCommand.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostConfirmPasswordReset/PostConfirmPasswordResetCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostConfirmPasswordReset/PostConfirmPasswordResetCommandValidator.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostRefreshToken/PostRefreshTokenCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostResetPassword/PostResetPasswordCommand.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostResetPassword/PostResetPasswordCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostResetPassword/PostResetPasswordCommandValidator.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostValidatePasswordResetConfirmationToken/PostValidatePasswordResetConfirmationTokenCommand.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Auth/PostValidatePasswordResetConfirmationToken/PostValidatePasswordResetConfirmationTokenCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/OAuth/GetExternalLoginCallback/GetExternalLoginCallbackCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Configurations/CustomTokenProvider.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/AuthController.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/OAuthController.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/SongController.cs
  RussianSpotify.API/RussianSpotify.API.WEB/appsettings.json
  spotify-react-app/src/commonComponents/Player/styles/Player.css
  spotify-react-app/src/functions/getCookieValueByName.ts
  spotify-react-app/src/http/authApi.ts
  spotify-react-app/src/http/subApi.ts
Labels: bugfix

#50 фикс по плейлистам
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Music/GetSongContentById/GetSongContentByIdQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/GetPlaylistsByFilter/GetPlaylistsByFilterQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PostAddPlaylistToFavourite/PostAddPlaylistToFavouriteCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PostCreatePlaylist/PostCreatePlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Services/Filters/PlaylistFilter/AlbumShuffledFilter.cs
  RussianSpotify.API/RussianSpotify.API.Core/Services/Filters/PlaylistFilter/PlaylistNameFilter.cs
Labels: bugfix

#53 Frontned: Song Card
  spotify-react-app/package-lock.json
  spotify-react-app/package.json
  spotify-react-app/src/App.tsx
  spotify-react-app/src/commonComponents/NavBar/NavBar.tsx
  spotify-react-app/src/commonComponents/Player/Player.tsx
  spotify-react-app/src/commonComponents/Playlist/Playlist.tsx
  spotify-react-app/src/commonComponents/SideBar/SideBar.tsx
  spotify-react-app/src/commonComponents/Song/Song.tsx
  spotify-react-app/src/commonComponents/Song/interfaces/ISong.ts
  spotify-react-app/src/functions/handleImageNotLoaded.ts
  spotify-react-app/src/http/songApi.ts
  spotify-react-app/src/pages/AccountPage/AccountPage.tsx
  spotify-react-app/src/pages/AccountPage/components/FavoriteMusic.tsx
  spotify-react-app/src/pages/AccountPage/components/FavouritePlaylist.tsx
  spotify-react-app/src/pages/AccountPage/styles/AccountPage.css
  spotify-react-app/src/pages/AuthorSongsPlaylist/AuthorSongsPlaylist.tsx
  spotify-react-app/src/pages/FavoriteSongsPlaylist/FavoriteSongsPlaylist.tsx
  spotify-react-app/src/pages/HomePage/components/DiscoveryCard.tsx
  spotify-react-app/src/pages/HomePage/components/PlaylistLittle.tsx
  spotify-react-app/src/pages/HomePage/components/PlaylistNormal.tsx
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/PlaylistPage/components/SongCard.tsx
  spotify-react-app/src/pages/PlaylistPage/styles/PlaylistPage.css
  spotify-react-app/src/pages/SearchPage/SearchPage.tsx
  spotify-react-app/src/pages/SearchPage/components/SearchAuthorCard.tsx
  spotify-react-app/src/pages/SearchPage/components/SearchPlaylistCard.tsx
  spotify-react-app/src/pages/SearchPage/styles/SearchPage.css
  spotify-react-app/src/utils/routeNames.ts
  spotify-react-app/src/utils/routes.ts
  spotify-react-app/src/utils/search/searchTypesProps.ts
  spotify-react-app/src/utils/sidebar/navigationElementsProps.ts
  spotify-react-app/src/utils/sidebar/playlistElementsProps.ts
Labels: enhancement, refactor

#54 Backend: AuthorByFilter fix
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Playlist/GetPlaylistsByFilter/GetPlaylistsByFilterRequest.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Author/GetAuthorsByFilter/GetAuthorsByFilterQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/GetPlaylistsByFilter/GetPlaylistsByFilterQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.UnitTests/RussianSpotify.API.UnitTests.csproj
Labels: bugfix, refactor

#52 Bugfix/auth front
  spotify-react-app/src/http/authApi.ts
  spotify-react-app/src/pages/ConfirmationCodePage/ConfirmationCodePage.tsx
  spotify-react-app/src/pages/LoginPage/components/AuthForm/AuthForm.tsx
  spotify-react-app/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
  spotify-react-app/src/utils/dto/user/userConfirmNewPasswordDto.ts
  spotify-react-app/src/utils/dto/user/userNewPasswordDto.ts
  spotify-react-app/src/utils/dto/user/userResetPasswordDto.ts
Labels: bugfix

#56 fix добавления в избранное того кто создал
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PostCreatePlaylist/PostCreatePlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommandHandler.cs
Labels: bugfix

#57 [bugfix/playlist-page] избавился от code duplicate
  spotify-react-app/src/assets/playlist/favorite-songs-playlist-image.png
  spotify-react-app/src/http/authorApi.ts
  spotify-react-app/src/http/songApi.ts
  spotify-react-app/src/pages/AccountPage/components/FavoriteMusic.tsx
  spotify-react-app/src/pages/AuthorSongsPlaylist/AuthorSongsPlaylist.tsx
  spotify-react-app/src/pages/FavoriteSongsPlaylist/FavoriteSongsPlaylist.tsx
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/PlaylistPage/enums/playlistTypes.ts
  spotify-react-app/src/utils/routes.ts
Labels: refactor

#58 Fullstack: Playlist Info Update
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Playlist/GetPlaylistsByFilter/GetPlaylistsByFilterRequest.cs
  RussianSpotify.API/RussianSpotify.API.Contracts/Requests/Playlist/PutPlaylist/PutPlaylistResponse.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/GetPlaylistsByFilter/GetPlaylistsByFilterQueryHandler.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommand.cs
  RussianSpotify.API/RussianSpotify.API.Core/Requests/Playlist/PutPlaylist/PutPlaylistCommandHandler.cs
  RussianSpotify.API/RussianSpotify.API.WEB/Controllers/PlaylistController.cs
  spotify-react-app/src/App.tsx
  spotify-react-app/src/assets/playlist/editPlaylist.png
  spotify-react-app/src/commonComponents/SideBar/components/CreatePlaylistModal/CreateOrEditPlaylistModal.tsx
  spotify-react-app/src/commonComponents/SideBar/components/CreatePlaylistModal/CreatePlaylistModal.tsx
  spotify-react-app/src/commonComponents/SideBar/interfaces/ICreateOrEditPlaylistModal.ts
  spotify-react-app/src/functions/editPlaylistWithFile.ts
  spotify-react-app/src/http/playlistApi.ts
  spotify-react-app/src/pages/HomePage/HomePage.tsx
  spotify-react-app/src/pages/PlaylistPage/PlaylistPage.tsx
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.css
  spotify-react-app/src/pages/SettingsPage/components/modals/editUserInfoModal/editUserInfoModal.tsx
  spotify-react-app/src/utils/dto/playlist/editPlaylistDto.ts
Labels: enhancement, bugfix
